package:
  name: metaclock
  version: 1.0.0

source:
  path: ../../metaclock

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv"

requirements:
  host:
    - python =3.6.10
    - setuptools
    - numpy
    - cython
    - pip
  run:
    - python =3.6.10
    - numpy =1.18.4
    - matplotlib =3.2.1
    - seaborn =0.10.1
    - samtools =1.3.1
    - bzip2 =1.0.8
    - blastn
    - biopython =1.76
    - bowtie2 >=2.0.0
    - pysam =0.15.4
    - mapdamage2
    - trimal >=1.4.1
    - cmseq =1.0.2
    - perl-bioperl
    - prokka
    - scikit-learn
    - ete3
    - dendropy
    - raxml
about:
  summary: This is a simple test for metaclock package
